# Generated by Django 4.2.7 on 2023-11-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_figure_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figure',
            name='color',
            field=models.CharField(max_length=255),
        ),
    ]
