name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 34.116.67.50
          username: ${{ secrets.kimd_22848 }}
          password: ${{ secrets.super22848 }}
          port: 8080
          script: |
            cd main_dr
            source /home/kimd_22848/venv/bin/activate
            git pull
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo supervisorctl restart all
